// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS9zGBt-d9bAheuNFHgIGBUCAlrvyIb6w',
    appId: '1:717074712559:web:291c4d9981e0afa602581a',
    messagingSenderId: '717074712559',
    projectId: 'db-ql-tro',
    authDomain: 'db-ql-tro.firebaseapp.com',
    storageBucket: 'db-ql-tro.firebasestorage.app',
    measurementId: 'G-2984GL46V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQXuyf-SatekKiWZ_zp9cIzBUOoTYxorE',
    appId: '1:717074712559:android:a57fe2fb5336225202581a',
    messagingSenderId: '717074712559',
    projectId: 'db-ql-tro',
    storageBucket: 'db-ql-tro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8xCNKt0YPb_5JKBRD2MevrYY40UOUQiQ',
    appId: '1:717074712559:ios:bed06396ba3dede202581a',
    messagingSenderId: '717074712559',
    projectId: 'db-ql-tro',
    storageBucket: 'db-ql-tro.firebasestorage.app',
    iosBundleId: 'com.example.doAnCuoiKi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8xCNKt0YPb_5JKBRD2MevrYY40UOUQiQ',
    appId: '1:717074712559:ios:bed06396ba3dede202581a',
    messagingSenderId: '717074712559',
    projectId: 'db-ql-tro',
    storageBucket: 'db-ql-tro.firebasestorage.app',
    iosBundleId: 'com.example.doAnCuoiKi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS9zGBt-d9bAheuNFHgIGBUCAlrvyIb6w',
    appId: '1:717074712559:web:734ac062455c233002581a',
    messagingSenderId: '717074712559',
    projectId: 'db-ql-tro',
    authDomain: 'db-ql-tro.firebaseapp.com',
    storageBucket: 'db-ql-tro.firebasestorage.app',
    measurementId: 'G-CMMQ0VFMSX',
  );
}
